language: go
go:
  - "1.9"
  - "1.10"
  - "tip"

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.12.3-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install: glide install
